### PR TITLE
Fix for issue #1390 caused by secure component having multiple childs

### LINKED ISSUE #1390: App crashes when a user with Bucket Read policies clicks on Browse button for a Bucket
As stated in the title, when a user with the following policy clicks on the Browse button for a Bucket, the app crashes:

```json
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Action": [
				"s3:ListMultipartUploadParts",
        "s3:ListBucketMultipartUploads",
        "s3:ListBucket",
        "s3:HeadBucket",
        "s3:GetObject",
        "s3:GetBucketLocation"
			],
			"Effect": "Allow",
			"Resource": [
				"arn:aws:s3:::*"
			],
			"Sid": ""
		}
	]
}
```

The errors displayed are as follows:

Screen Shot 2022-01-12 at 6 53 00 PM
Screen Shot 2022-01-12 at 6 53 19 PM
Screen Shot 2022-01-12 at 6 53 38 PM

After further investigation, it seems like the extra `input` element here is causing an error while the SecureComponent is rendering, and seems like we can remove it as we already have the input element outside the SecureComponent:
https://github.com/minio/console/blob/1871f2bf9e2bc63a222344b853756fd2babcfc72/portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx#L1222-L1229

### PR DESCRIPTION
**Pull request by dvaldivia**
Fixes #1390 

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

### CODE REVIEW

File: portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx [hunk 1]
```diff
@@ -1202,26 +1202,30 @@ const ListObjects = ({
...
-                    variant={"outlined"}
-                  />
-                  <input
-                    type="file"
-                    multiple
-                    onChange={handleUploadButton}
-                    style={{ display: "none" }}
-                    ref={folderUpload}
-                  />
+                  <>
```
Comment (bexsoft) [inline portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx:1205]: Please use `<Fragment>` for consistency

**Review by bexsoft — CHANGES_REQUESTED** [review]

File: portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx (hunk 1 above)
Comment (dvaldivia) [reply portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx:1205]: I see most examples on react using this shorthand, we should start adopting it

Comment (bexsoft) [reply portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx:1205]: Then we would need to change across all the code. I think Fragment is better because is more clear what this is referring to.

**Review by bexsoft — CHANGES_REQUESTED** [review]

File: portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx [hunk 2]
```diff
@@ -1202,26 +1202,28 @@ const ListObjects = ({
...
-                    variant={"outlined"}
-                  />
-                  <input
-                    type="file"
-                    multiple
-                    onChange={handleUploadButton}
-                    style={{ display: "none" }}
-                    ref={folderUpload}
-                  />
+                  <Fragment>
```
Comment (bexsoft) [inline portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx:1205]: Thank you! =D

**Review by bexsoft — APPROVED** [review]

**Review by jinapurapu — APPROVED** [review]

**Review by cniackz — APPROVED** [review]
Learning from it:
A fragment lets us group multiple JSX elements without adding an extra wrapper node.

**Review by adfost — APPROVED** [review]
