### PR TITLE
Object Browser Refactor

### LINKED ISSUE #3001: Bucket shows empty when a new object is uploaded
If an object is selected and a new object gets uploaded, the UI now lists no items instead of reloading and listing the new item.

Note:
Same happens when multiple objects get selected and deleted.

Before uploading object:
Screenshot 2023-08-16 at 10 34 08 AM

After uploading new object:
Screenshot 2023-08-16 at 10 34 24 AM

## Expected Behavior
It should list the new item including existing items

## Current Behavior
It shows an empty list

## Possible Solution

Path stays on the previous object selected which might be causing some issues.

## Steps to Reproduce (for bugs)
- On a bucket with objects, select an object
- The menu on the right should show up (with actions Download, preview, etc.)
- Upload a new object
- [Bug] Here the list shows empty and still pointing to the previous object.

## Your Environment

* MinIO version used (`minio --version`): RELEASE.2023-08-09T23-30-22Z

### PR DESCRIPTION
**Pull request by bexsoft**
fixes #3001 

## What does this do?

Simplified the Object Browser code by changing the location of Websockets to be a middleware as well as simplifying the logic to handle the object browser paths

- Refactored navigation to be handled only with URL
- Refactored & simplified websocket
- Updated components to use mds
- Fixed an issue with Anonymous access and file selection
- Fixed an issue with anonymous access and download selection click
- Fixed an issue with object details selection on root path from a bucket
- Simplified reducer

### CODE REVIEW

**Comment by jinapurapu** [comment]
After creating a path, "Loading" remains, drag and drop upload doesn't work. 



https://github.com/minio/console/assets/65002498/9de26a59-a502-4424-ae69-93de7663c089

**Comment by bexsoft** [comment]
> After creating a path, "Loading" remains, drag and drop upload doesn't work.
> 
>  Screen.Recording.2023-10-02.at.11.09.53.AM.mov

Fixed: 
Screen Recording 2023-10-02 at 1 50 23 p m 2023-10-02 13_51_28

**Comment by jinapurapu** [comment]
Clicking arrow icon to invert object list order causes "Loading" to hang:

https://github.com/minio/console/assets/65002498/c3700d31-2f33-48e2-ba30-9b788f2e39b3

File: portal-ui/src/websockets/objectBrowserWSMiddleware.ts [hunk 1]
```diff
@@ -0,0 +1,231 @@
...
+              return;
+            }
+
+            if (
+              response.error ===
+              "The Access Key Id you provided does not exist in our records."
+            ) {
+              // Session expired.
+              window.location.reload();
+            } else if (response.error === "Access Denied.") {
```
Comment (cesnietor) [inline portal-ui/src/websockets/objectBrowserWSMiddleware.ts:103]: could we use codes, instead of strings for these type of validations?
Cause the thext response could change any time and we wouldn't know that it could break this.

File: portal-ui/src/websockets/objectBrowserWSMiddleware.ts [hunk 2]
```diff
@@ -0,0 +1,231 @@
...
+  WebsocketResponse,
+} from "../screens/Console/Buckets/ListBuckets/Objects/ListObjects/types";
+import { decodeURLString, encodeURLString } from "../common/utils";
+import { permissionItems } from "../screens/Console/Buckets/ListBuckets/Objects/utils";
+import { setErrorSnackMessage } from "../systemSlice";
+
+let wsInFlight: boolean = false;
+let currentRequestID: number = 0;
+
+export const objectBrowserWSMiddleware = (
```
Comment (cesnietor) [inline portal-ui/src/websockets/objectBrowserWSMiddleware.ts:44]: do you mind adding more context on what this refactor is doing? vs the previous one? just fo have it documented in the PR.

**Review by cesnietor — COMMENTED** [review]
Tested different scenarios with paths, tracing, anonymous buckets, deleting and adding multiple objects. All seems great.! Just left few comments.

File: portal-ui/src/websockets/objectBrowserWSMiddleware.ts (hunk 1 above)
Comment (bexsoft) [reply portal-ui/src/websockets/objectBrowserWSMiddleware.ts:103]: Let me check as we are not returning response codes in the web socket. We do have a test to validate this behavior

**Comment by bexsoft** [comment]
> Clicking arrow icon to invert object list order causes "Loading" to hang:
> 
>  Screen.Recording.2023-10-02.at.1.40.10.PM.mov

Fixed

File: portal-ui/src/websockets/objectBrowserWSMiddleware.ts (hunk 1 above)
Comment (bexsoft) [reply portal-ui/src/websockets/objectBrowserWSMiddleware.ts:103]: Will fix this in an upcoming PR as some extra changes need to be done

Comment (cesnietor) [reply portal-ui/src/websockets/objectBrowserWSMiddleware.ts:103]: sounds good.

**Review by cesnietor — APPROVED** [review]

**Review by jinapurapu — APPROVED** [review]
