### PR TITLE
fix event dest icons not loading when subpath is configured

### LINKED ISSUE #3151: Using nginx proxy, adding event page icon is missing
## Expected Behavior

I used the nginx proxy console and added the prefix /minio-console. When I entered the add event page, I found that the icon was missing because the path requested to obtain the icon did not include the prefix /minio-console. As a result I had to modify the nginx configuration to re-proxy the request to the correct address whenever the request suffix was -logo.svg

image

## Possible Solution
Had to add Nginx configuration to temporarily solve
```nginx
	location / {
		#Temporarily solve the problem of missing icons
		if ($request_uri ~* "-logo\.svg$") {
			rewrite ^/(.*)$ https://yourdomain.cn/minio-console/$1 permanent;
		}
		proxy_set_header Host $http_host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;

		proxy_connect_timeout 300;
		# Default is HTTP/1, keepalive is only enabled in HTTP/1.1
		proxy_http_version 1.1;
		proxy_set_header Connection "";
		chunked_transfer_encoding off;

		proxy_pass http://minio;
	}
		
	location /minio-console/ {
		rewrite ^/minio-console/(.*) /$1 break;
		proxy_set_header Host $http_host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-NginX-Proxy true;

		# This is necessary to pass the correct IP to be hashed
		real_ip_header X-Real-IP;

		proxy_connect_timeout 300;

		# To support websockets in MinIO versions released after January 2023
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		# Some environments may encounter CORS errors (Kubernetes + Nginx Ingress)
		# Uncomment the following line to set the Origin request to an empty string
		# proxy_set_header Origin '';
		chunked_transfer_encoding off;
		proxy_pass http://minio_console;
        }
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

### PR DESCRIPTION
**Pull request by prakashsvmx**
fix event dest icons not loading when subpath is configured

fixes #3151
how does it look:
Screenshot from 2023-12-26 15-10-40

### CODE REVIEW

**Review by bexsoft — APPROVED** [review]
LGTM

**Review by dvaldivia — APPROVED** [review]

File: portal-ui/src/screens/Console/EventDestinations/utils.ts [hunk 1]
```diff
@@ -48,65 +47,69 @@ export class DestType {
   static Func: string = "functions";
 }
 
+const getImgBaseURL = () => {
```
Comment (dvaldivia) [inline portal-ui/src/screens/Console/EventDestinations/utils.ts:50]: I think we could use `${document.baseURI}` directly instead of this function
