### PR TITLE
Fixed issue with object browser icons & long names

### LINKED ISSUE #386: Some elements in object browser don't have icons
Screen Shot 2020-11-11 at 8 58 02 PM

### PR DESCRIPTION
**Pull request by bexsoft**
fixes #386

## What does this do?

Fixes an issue with long object names & icons.

## How does it look?

Screen Shot 2020-11-12 at 1 42 19 PM

### CODE REVIEW

File: portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx [hunk 1]
```diff
@@ -374,7 +380,9 @@ const ListObjects = ({
     return (
       <div className={classes.fileName}>
         <div className={icon} />
-        <span>{splitItem[splitItem.length - 1]}</span>
+        <span className={classes.fileNameText}>
+          {splitItem[splitItem.length - 1]}
```
Comment (Alevsk) [inline portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx:384]: here if length its `0` we will end with `index[-1]`, do we validate that above this code?

**Review by Alevsk — DISMISSED** [review]

File: portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx (hunk 1 above)
Comment (bexsoft) [reply portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx:384]: In this case length will never be 0 as split always return at least one element when you pass any string:

Screen Shot 2020-11-12 at 1 58 11 PM

**Review by dvaldivia — APPROVED** [review]

**Review by Alevsk — APPROVED** [review]
