### PR TITLE
Fix Tenant Details Bugs

### LINKED ISSUE #584: Expand Tenant doesn't indicate a name

### LINKED ISSUE #585: Expand Tenant on UI doesn't add anti Affinity clauses

### LINKED ISSUE #586: Pool list doesn't show the proper names of the pool even if the CRD lists one

### PR DESCRIPTION
**Pull request by dvaldivia**
This fixes #584 by making the expand set a name for the pool
This fixes #585 by making the expand set an affinity for the pool
This fixes #586 by generating a pool name if it's not indicated only

Also adds namespace to the list of columns of  tenant

### CODE REVIEW

File: restapi/admin_tenants.go [hunk 1]
```diff
@@ -381,12 +381,14 @@ func getTenantInfoResponse(session *models.Principal, params admin_api.TenantInf
...
-		return nil, prepareError(err)
+		// we can tolerate this error
+		log.Println(err)
 	}
 	//console service
 	conSvc, err := k8sClient.getService(ctx, minTenant.Namespace, minTenant.ConsoleCIServiceName(), metav1.GetOptions{})
 	if err != nil {
-		return nil, prepareError(err)
+		// we can tolerate this error
+		log.Println(err)
```
Comment (cesnietor) [inline restapi/admin_tenants.go:391]: minSvc and conSvc can be nil, please do the proper validations.

**Review by cesnietor — CHANGES_REQUESTED** [review]

File: restapi/admin_tenants.go (hunk 1 above)
Comment (dvaldivia) [reply restapi/admin_tenants.go:391]: nice catch, fixed

**Review by Alevsk — DISMISSED** [review]

File: portal-ui/src/screens/Console/Tenants/TenantDetails/utils.ts [hunk 2]
```diff
@@ -0,0 +1,43 @@
+// This file is part of MinIO Console Server
+// Copyright (c) 2020 MinIO, Inc.
```
Comment (bexsoft) [inline portal-ui/src/screens/Console/Tenants/TenantDetails/utils.ts:2]: Please change this to be 2021

File: portal-ui/src/screens/Console/Menu/Menu.tsx [hunk 3]
```diff
@@ -317,7 +317,7 @@ const Menu = ({ userLoggedIn, classes, pages, operatorMode }: IMenuProps) => {
       icon: <WarpIcon />,
     },
     {
-      group: "License",
+      group: "Operator",
```
Comment (bexsoft) [inline portal-ui/src/screens/Console/Menu/Menu.tsx:320]: Why are we changing it to Operator? This would be confusing for customers since they will think that you can access to operator here but it will redirect you to license page

**Review by bexsoft — CHANGES_REQUESTED** [review]

File: portal-ui/src/screens/Console/Menu/Menu.tsx (hunk 3 above)
Comment (dvaldivia) [reply portal-ui/src/screens/Console/Menu/Menu.tsx:320]: the intention is to remove the line dividir, but i think this also removes license from the regular console, I'll re-add that

**Review by bexsoft — DISMISSED** [review]
LGTM

**Review by cesnietor — APPROVED** [review]

**Review by cesnietor — CHANGES_REQUESTED** [review]
please make assets

**Review by Alevsk — APPROVED** [review]

**Review by cesnietor — APPROVED** [review]
